#!/bin/bash

def_colors () {
        # 特性
        normal='\033[0m';       bold='\033[1m';         dim='\033[2m';          under='\033[4m';
        italic='\033[3m';       noitalic='\033[23m';    blink='\033[5m';
        reverse='\033[7m';      conceal='\033[8m';      nobold='\033[22m';
        nounder='\033[24m';     noblink='\033[25m';
        # 前景
        black='\033[30m';       red='\033[31m';         green='\033[32m';       yellow='\033[33m';
        blue='\033[34m';        magenta='\033[35m';     cyan='\033[36m';        white='\033[37m';
        # 背景
        bblack='\033[40m';      bred='\033[41m';
        bgreen='\033[42m';      byellow='\033[43m';
        bblue='\033[44m';       bmagenta='\033[245m';
        bcyan='\033[46m';       bwhite='\033[47m';
}

def_colors

def_usage () {
		echo -e "\teg."
		echo -e "\t${cyan}#${0} *.elf main${normal}"
}

#
## Init
#
#ELF=./preloader_k95v2_1.elf
ELF=${1}
FUNC=${2}
if [ -f ${ELF} ];then
	if [ -z ${FUNC} ];then
		echo -e "${red}Wrong: Need a par which the function name you find.${normal}"
		def_usage
		exit 1
	fi
else
	echo -e "${red}Wrong: It's not a elf.${normal}"
	def_usage
	exit 1
fi

#
## Find
#
ADDR=`nm ${ELF} | grep -w ${FUNC} | awk -F ' ' '{print $1}'`
if [ -z ${ADDR} ];then
	echo -e "${red}Wrong:${normal}"
	echo -e "${red}\tNot found the func, may be this is a static function(will build inline)..${normal}"
	echo -e "${red}\tOr may be you input a wrong func name..${normal}"
	def_usage
	exit 1
fi
PATH=`addr2line -e ${ELF} ${ADDR}`

#
## Output Info
#
echo -e "\n${blue}${bold}${FUNC}()${normal}"
echo -e "${magenta}\
-------------------------------------------\
-------------------------------------------\
${normal}"
echo -e   "${yellow}${PATH}${normal}\n"
